# Generated by Django 4.2.11 on 2024-04-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medventory', '0002_alter_vendor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=64)),
                ('unit_abbreviation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=64)),
                ('trade_name', models.CharField(max_length=64)),
                ('dose', models.FloatField()),
                ('item_number', models.CharField(max_length=64)),
                ('barcode', models.CharField(max_length=64)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medventory.unit')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medventory.vendor')),
            ],
        ),
    ]
