# Generated by Django 4.2.11 on 2024-04-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medventory', '0004_remove_medication_trade_name_tradename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradename',
            old_name='trade_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='tradename',
            old_name='generic_name',
            new_name='generic',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='trade_name',
        ),
    ]
